# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20161221_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile2',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Type your primary address here'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
