# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20161221_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
