# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20161221_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
