# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
