# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_description',
            field=models.TextField(max_length=1000),
        ),
    ]
