# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161221_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_description',
            field=models.TextField(max_length=10000),
        ),
    ]
