# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20161221_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_image1',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='games',
            name='game_image2',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='games',
            name='game_image3',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
