# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161222_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_image1',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_image2',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_image3',
            field=models.FileField(upload_to=b''),
        ),
    ]
