# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20161224_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='arcade',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='bike',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='car',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='dirt',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='road',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='simulator',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='games',
            name='truck',
            field=models.BooleanField(),
        ),
    ]
