# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='order',
        ),
    ]
