# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_recommend_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='recomm',
            new_name='recomend',
        ),
    ]
