# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20170104_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.games')),
            ],
        ),
    ]
