# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_mouseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouseorder',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mouse'),
        ),
    ]
