# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170104_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='wireless',
            field=models.BooleanField(default=False),
        ),
    ]
